version: '2'
services:

  nginx:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-nginx
    ports:
    - "80:80"
    volumes:
      - type: bind
        source: ./
        target: /var/www/portfolio
      - type: bind
        source: ./docker/config/sites/frontend.nginx.conf
        target: /etc/nginx/sites-enabled/frontend.nginx.conf
    depends_on:
      - php
    networks:
      - deploy_default

  mysql:
    image: mariadb:10.3
    ports:
      - "33066:3306"
    volumes:
      - type: bind
        source: ../docker/init_mysql
        target: /docker-entrypoint-initdb.d:rw
      - type: volume
        source: portfolio_db_data
        target: /var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "portfolio"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "portfolio"
    networks:
      - deploy_default

  php:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-php
    volumes:
      - type: bind
        source: ./
        target: /var/www/portfolio
    environment:
      - XDEBUG_CONFIG=remote_host=host.docker.local-network remote_enable=1
      - PHP_IDE_CONFIG=serverName=php
      - DB_DSN=mysql:host=mysql;dbname=portfolio;
      - DB_USER=portfolio
      - DB_PASSWORD=1
    networks:
      - deploy_default


volumes:
  portfolio_db_data:
    name: portfolio_db_data
    driver: local


networks:
  deploy_default:
    name: deploy_default
    driver: bridge